name: build
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        parameter-set:
          - 1-slot
          - 4-slot
          - 4-slot-mini
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the STL file
        uses: mmalecki/openscad-build-action@optional-parameter-sets
        with:
          input-file: 'framework-expansion-card-stand.scad'
          output-file: 'framework-expansion-card-stand-${{ matrix.parameter-set }}.stl'
          customizer-parameter-file: 'parameters.json'
          customizer-parameter-set: ${{ matrix.parameter-set }}

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'framework-expansion-card-stand.stl'
          default_author: github_actions
          message: 'Build the STL file'
          push: true
