name: build
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        parameter-set:
          - 1-slot
          - 4-slot
          - 4-slot-mini
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the STL file
        uses: mmalecki/openscad-build-action@optional-parameter-sets
        with:
          input-file: 'framework-expansion-card-stand.scad'
          output-file: 'framework-expansion-card-stand-${{ matrix.parameter-set }}.stl'
          customizer-parameter-file: 'parameters.json'
          customizer-parameter-set: ${{ matrix.parameter-set }}

      - name: Upload the built STL file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.parameter-set }}
          path: 'framework-expansion-card-stand-${{ matrix.parameter-set }}.stl'
